### ISSUE TITLE
dmtx-utils installation via CentOS7 and OS X 10.8+ 

### ISSUE THREAD

**Issue by swvanderlaan** [dmtx/dmtx-utils#2]
Hi,
I'm trying to install dmtx-utils via `brew install dmtx-utils` and via `git`. It throws an error :

> checking for MAGICK... no
> configure: error: dmtxread/dmtxwrite requires Wand >= 6.2.4
> Error: dmtx-utils was moved to homebrew-boneyard because it has unfixable issues.

After considering many options, I've come to the conclusion that it may well has to do with the specific version of ImageMagick that is installed. It appears that Wand.pc is not even present in ImageMagick 7.0.4-8 (which is currently the current version). 

Do you have any suggestions as to how to solve this issue?

Best,

Sander

**Comment by msva** [comment]
With 6.9.7.6 on Gentoo I have:
```
$ qlist imagema | grep 'Wand\.pc$'
/usr/lib64/pkgconfig/MagickWand.pc
/usr/lib64/pkgconfig/Wand.pc
```
Definitelly not a CentOS, though ;)
And 7.0 is "masked" for installation here because of:
```
# Lars Wendler <polynomial-c@gentoo.org> (2 May 2016)
# Broken reverse deps. At least one header file has been moved around.
>=media-gfx/imagemagick-7.0.1.0
```
Looks like CentOS prefered to just step by and ignore that ;)

Also, it seems, like `Wand` is just "alias" for `MagickWand`, which, in turn, alias to `MagickWand-6.Q16HDRI` (where 6 = major version, Q16 = selected (on build time) quantum depth, and HDRI is `--enabled-hdri`.

So, technically, I can patch buildsystem to autodetect all of that, but:
1) is it really needed and unavoidable in your setup? // can you show the listing of content of imagemagick package grepped by `Wand\.pc$`? Or by `\.pc$` if it will be empty.
2) at least tonight or tomorrow

**Comment by msva** [comment]
@swvanderlaan can you test the fix?

**Comment by swvanderlaan** [comment]
I will test it yeah. We will get back on it.

**Comment by swvanderlaan** [comment]
Tested. Our suite (https://github.com/swvanderlaan/slideToolkit/blob/master/guides/INSTALL.OSX.md) seems to be working again. Awesome. Thanks!

**Comment by swvanderlaan** [comment]
Hoping you read this. The only thing now, then is to fix the `Homebrew` version of `dmtx-utils`. If I install it manually from source it works. But via `Homebrew` using `brew install dmtx-utils` I still get the same error:

> Mac-mini-van-Sander:~ swvanderlaan$ brew install dmtx-utils
> ==> Installing dmtx-utils from homebrew/boneyard
> ==> Downloading https://downloads.sourceforge.net/project/libdmtx/libdmtx/0.7.4/dmtx-utils-0.7.4.zip
> ==> Downloading from https://netcologne.dl.sourceforge.net/project/libdmtx/libdmtx/0.7.4/dmtx-utils-0.7.4.zip
> ######################################################################## 100.0%
> ==> ./configure --prefix=/usr/local/Cellar/dmtx-utils/0.7.4_2
> Last 15 lines from /Users/swvanderlaan/Library/Logs/Homebrew/dmtx-utils/01.configure:
> checking whether to build static libraries... yes
> checking whether clang and cc understand -c and -o together... yes
> checking for library containing atan2... none required
> checking for pkg-config... /usr/local/opt/pkg-config/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for DMTX... yes
> checking sysexits.h usability... yes
> checking sysexits.h presence... yes
> checking for sysexits.h... yes
> checking getopt.h usability... yes
> checking getopt.h presence... yes
> checking for getopt.h... yes
> checking for getopt_long... yes
> checking for MAGICK... no
> configure: error: dmtxread/dmtxwrite requires Wand >= 6.2.4
> 
> Error: dmtx-utils was moved to homebrew-boneyard because it has unfixable issues.
> Please do not file any issues about this. Sorry!
> 

Seems easy to fix now with the above fix, but I'm not an experienced coder, so I might be mistaken. Am I right?

**Comment by msva** [comment]
it is pretty easy to fix this by apply the same patch, as in last commit. But it is package maintainer in homebrew, who shoould do that. I can't patch it there for them.

Although, I can release a new version with this fix from current git HEAD (it is pretty stable).

**Comment by msva** [comment]
@swvanderlaan, can you test if current git HEAD **working** (not only builds) 
fine with ImageMagick7?

If so, I'll remark new HEAD as 0.7.5 tag and re-release it (and then we'll go 
to @Homebrew tracker) :)

**Comment by msva** [comment]
Okay. I checked it myself.

So, let's go in homebrew tracker.
